/** Pack A display names — keep in sync with migration 021. */
export const ZONING_RIGHTS_PACK_A_NAMES = [
  "Post Office",
  "Castle",
  "School",
  "Nightclub",
  "Hot Dog Stand",
  "Stadium",
  "Bookstore",
  "Haunted Mansion",
  "Safe Injection Site",
  "Opera",
  "French Restaurant",
  "Rage Room",
  "Tax Service Center",
  "Buddhist Temple",
  "Exhibition Center",
  "Chocolate Factory",
  "Excavation Site",
  "Casino",
  "Aquarium",
  "Graffiti Tunnel",
  "Medieval Tavern",
  "Bakery",
  "Printing Shop",
  "Organic Supermarket",
  "Dry Cleaner",
  "Gas Station",
  "Distillery",
  "Outlet Mall",
  "Pharmacy",
  "College",
  "Community Garden",
  "Camp Ground",
  "Dog Park",
  "Yoga Retreat",
  "Bus Terminal",
  "Family Resource Center",
  "Bank",
  "Job Center",
  "Coffee",
  "Drive Through",
  "Mini Golf",
  "Visitor Center",
  "Thrift Shop",
  "Board Game Cafe",
  "Five Star Hotel",
  "Barbershop",
  "Gym",
  "Mermaid Pond",
  "Library",
  "Skyscraper",
  "Public Toilets",
  "Coal Mine",
  "Local Newspaper",
  "Condominiums",
  "Comedy Club",
  "Famous Statue",
  "Botanical Garden",
  "Public Housing",
  "Daycare",
  "Fancy Spa",
  "Youth Hostel",
  "Hourly Motel",
  "Dive Bar",
  "Animal Shelter",
  "Cemetery",
  "Retirement Home",
  "Skate Park",
  "Candy Shop",
  "Recycling Center",
  "Alien Abduction Site",
  "Synagogue",
  "Chinese Buffet",
  "Police Station",
  "Tattoo Parlor",
  "Business School",
  "Playground",
  "Co-working Space",
  "Mental Health Clinic",
  "Community Center",
  "Courthouse",
  "Karaoke Bar",
  "Arcade",
  "Massage Parlor",
  "Circus Park",
  "Art Gallery",
  "Movie Theatre",
  "Farmers Market",
  "Prison",
  "Production Studio",
  "Doomsday Bunker",
  "Baseball Field",
  "Jewelry Boutique",
  "Robot Factory",
  "Celebrity Residence",
  "Fire Station",
  "Modeling Agency",
  "Military Museum",
  "Gated Community",
  "Mosque",
  "Main Square",
  "Consulate",
  "Observatory",
  "Soap Factory",
  "5G Cell Tower",
  "Boxing Arena",
  "Alcoholics Anonymous",
  "Fish Shop",
  "Garage Sale",
  "Train Station",
  "Catacombs",
  "Ice Cream Truck",
  "Hospital",
  "Swimming Pool",
  "Pottery Studio",
  "Hardware Store",
  "Research Lab",
  "Church",
  "Intelligence Agency",
  "Cattle Ranch",
  "Amusement Park",
  "Nuclear Plant",
] as const;
